### PR TITLE
uvmon v2

### PR DESCRIPTION
**Pull request by chaosgame**
Hello @dudeche, @kellyellis, @sboora, @dpup, @koop, 

Please review the following commits I made in branch 'nathan-uvmon2'.

005cb594984e93be2f1e45cf67abef601bdf7ac1 (2015-09-04 09:19:17 -0700)
uvmon v2
Big changes:
- Enable/disable profiling for event loop ticks over 100ms
- Log stats as a histogram
- Use uv_now correctly and capture the entire tick duration.

R=@dudeche
R=@kellyellis
R=@sboora
R=@dpup
R=@koop

Test plan: 'Tested locally with standard.dev'

### CODE REVIEW

**Comment by dpup** [comment]
+ @nicksantos

**Comment by sboora** [comment]
Is this something we can turn on with a signal, or is 100ms too aggressive to begin with?

**Comment by chaosgame** [comment]
@sboora Manual testing suggests that the overhead will be less than 2% -- at that rate, I'm not super worried.

**Comment by chaosgame** [comment]
Verbal LGTM from @traviscrawford

**Pull request merged**
